title: OCI Hello Logging Analytics
description: Explore how to use OCI Logging Analytics with Kubernetes
informationalText: This stack deploys a Kubernetes Cluster, Fluentd, Node.js App, and create Logging Analytics

schemaVersion: 1.1.0
version: "20220414"

logoUrl: https://pbs.twimg.com/profile_images/1108568611113689088/9bfcUA9t_400x400.png

locale: "en"
variableGroups:
  - title: "Basic Hidden"
    variables:
      - region
      - tenancy_ocid
      - current_user_ocid
      - fingerprint
      - user_ocid
      - cluster_kube_config_expiration
      - cluster_kube_config_token_version
      - private_key_path
      - availability_domain
      - cluster_endpoint_visibility
      - cluster_options_add_ons_is_kubernetes_dashboard_enabled
      - cluster_options_add_ons_is_tiller_enabled
      - cluster_workers_visibility
      - generate_public_ssh_key
      - image_operating_system
      - image_operating_system_version
      - k8s_version
      - network_cidrs
      - node_pool_boot_volume_size_in_gbs
      - node_pool_name
      - node_pool_node_shape_config_memory_in_gbs
      - node_pool_node_shape_config_ocpus
      - node_pool_shape
      - num_pool_workers
      - public_ssh_key
    visible: false
  - title: "General Configuration"
    variables:
      - compartment_ocid
  - title: "Compute Details"
    variables:
      - ${cluster_name}

variables:
  compartment_ocid:
    type: oci:identity:compartment:id
    title: "Compartment"
    description: "The compartment in which to create the stack"
    required: true
  cluster_name:
    type: string
    minLength: 3
    maxLength: 255
    pattern: "^[a-z][a-zA-Z0-9]+$"
    title: "Cluster Name"
    description: "Enter your Cluster name, it will be use for other resource names"
    default: "HelloLogan"
    required: true
